### ISSUE TITLE
Seattle Kraken

### ISSUE THREAD

**Issue by marty56-v** [jalgraves/jockbot_nhl#16]
I cannot get anything to work with this because I don't believe it accounts for the Seattle Kraken having been added to the league. I always get an error telling me that it doesn't recognize the team "Seattle Kraken"

**Comment by jalgraves** [comment]
Hi @marty56-v , thanks for bringing this to my attention as I haven't had a chance this season to update the code. I will hopefully have the new franchise added in the next few days.

**Comment by jalgraves** [comment]
I added Seattle Kraken to config. Sorry for the delay.
